### ISSUE TITLE
Open and Browse buttons don't open the file browser

### ISSUE THREAD

**Issue by SolsticeSpectrum** [BlackMIDIDevs/wasabi#52]
I am on Arch Linux using i3wm and Nautilus as file manager. Pressing the "Open" button or the "Browse" button in XSynth -> SFZ Path does not open the file manager.

Workaround: Using drag&drop works for midis and I can type out the path for SFZ

**Comment by DarkReaper231** [comment]
If anyone experiences this issue and finds this issue, git clone this repository and edit this in Cargo.toml
```toml
rfd = { version = "0.12.0", default-features = false, features = [
    'xdg-portal',
] }
```
to
```toml
rfd = { version = "0.12.0" }
```
then run `cargo run --release` and you'll find the binary in `target/release/`

**Comment by arduano** [comment]
Forgot to respond to this before, but basically you need to install whatever corresponding "portals" program you have for your DE. Portals are a standard thing used by many things including flatpaks and other programs that want to use the native DE's file picker. Without portals, wasabi uses the primitive gtk file picker. We added portals here to fix that.

**Comment by SolsticeSpectrum** [comment]
That wasn't the issue, I had that portal but you fixed it by changing the rfd thing. Anyway there is a small bug with this. Usually when you have such file dialog, it remembers last folder accessed, aka if I open midi from specific folder, next time it should open that folder. Instead it always goes to home folder and the terminal output says some error corresponding to that. I can check what the error says when I get home in 8 hours.

**Comment by arduano** [comment]
Personally I get no errors in the terminal when opening stuff so I don't know if I could reproduce that

As for remembering the last folder to open from, that's a separate feature that should be implemented as it requires storing/caching that path in some config manually. Feel free to make a new issue for that
