### ISSUE TITLE
How can I run the MacOS version of this?

### ISSUE THREAD

**Issue by qingy1337** [BlackMIDIDevs/wasabi#67]
I'm not sure how to actually run it...

**Comment by Kaydax** [comment]
Transferring this over to wasabi as this is more related to getting wasabi to run on MacOS via MoltenVK

**Comment by arduano** [comment]
Interesting yeah, @qingy1337 fyi none of the wasabi devs use macs, we just cross-compiled to macos because Rust lets us easily do that. We are very open to mac-related code contribution if you're capable of doing that

**Comment by qingy1337** [comment]
@arduano Alright, I'm a bit of a programmer myself, I can try to get familiar with this.

**Comment by arduano** [comment]
We use the rust `vulkano` for running vulkan, and `winit` to run window management. If those can be made compatible with mac (likely vulkano is the main problem), then it should run on mac fine

**Comment by Kaydax** [comment]
> We use the rust `vulkano` for running vulkan, and `winit` to run window management. If those can be made compatible with mac (likely vulkano is the main problem), then it should run on mac fine

From reading the vulkano readme and docs, it states it supports MacOS via MoltenVK just fine

**Comment by qingy1337** [comment]
I just created a PR for a fix that actually let me open wasabi, but I'm running into another error... :)
```
thread 'main' panicked at core/src/panicking.rs:229:5:
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.
zsh: abort      cargo run
```

**Comment by Kaydax** [comment]
@qingy1337 Your PR disables geometry shaders, which is required to run wasabi as our shaders depend on it

**Comment by qingy1337** [comment]
@Kaydax OK, maybe I can find a workaround for this, thanks for letting me know!

**Comment by qingy1337** [comment]
Ok I just got a Windows VM :) this is me running Piano from Above, although it is pretty slow, I'm gonna try and get wasabi running on this guy.
![Screenshot 2024-09-13 103357](https://github.com/user-attachments/assets/02ae8d4a-f296-47d2-ad1a-1adccad9f8ac)
