### ISSUE TITLE
Automatically Reload XSynth after modifying Soundfonts

### ISSUE THREAD

**Issue by Softy107** [BlackMIDIDevs/wasabi#82]
When adding, modifying or ordering soundfonts, no changes in rendering are apparent until the reload button in the synth tab is pressed.

Not sure why this is the case, but I think that either another button should be added to reload the synthesizer in the soundfonts tab, or the synth should automatically reload after changes to the sf list.

**Comment by arduano** [comment]
In theory, xsynth supports changing soundfonts without needing to reload the synth.
@MyBlackMIDIScore does your audio settings window propagate soundfont updates automatically? I cant remember

**Comment by MyBlackMIDIScore** [comment]
Since v1.0.0 any changes to the soundfont list will be applied after the user presses the check button ("Apply SoundFont List") on the bottom right in the "SoundFonts" settings page. No need to reload the synth indeed.

@Softy107 Does this button not work for you?

**Comment by Softy107** [comment]
I am very sorry as I did not notice the check mark button.
The button does work, I just did not see it somehow.
Sorry to bother.

**Comment by Kaydax** [comment]
This is horrible UI design, it should load the soundfont on save, not by clicking a separate button
