### ISSUE TITLE
[BUG] the Midi Player Wont Start

### ISSUE THREAD

**Issue by Bartosz8291** [BlackMIDIDevs/wasabi#85]
It Crashed After Running Normally I Tried With CMD and:
Using device: GeForce GT 740M (type: DiscreteGpu)
thread 'main' panicked at src\renderer\swapchain.rs:76:10:
called `Result::unwrap()` on an `Err` value: a validation error occurred

Caused by:
    `create_info.present_mode` is not supported for `surface`

Vulkan VUIDs:
    VUID-VkSwapchainCreateInfoKHR-presentMode-01281
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by desatur** [comment]
The last driver for this GPU doesn't support Vulkan `1.3`, I only see `1.2.175` and is probably missing a lot of features

**Comment by Kaydax** [comment]
Your GPU is way to outdated, and is considered deprecated by NVIDIA as well. Wasabi needs the latest vulkan api to run, which your card does not support
