### ISSUE TITLE
INSTANT ISSUE

### ISSUE THREAD

**Issue by Bartosz8291** [BlackMIDIDevs/wasabi#87]
after i open after like 2 seconds it closes and it's with white screen

**Comment by Bartosz8291** [comment]
wasabi-windows-x86_64.exe
Using device: GeForce GT 740M (type: DiscreteGpu)
thread 'main' panicked at src\renderer\swapchain.rs:76:10:
called `Result::unwrap()` on an `Err` value: a validation error occurred

Caused by:
    `create_info.present_mode` is not supported for `surface`

Vulkan VUIDs:
    VUID-VkSwapchainCreateInfoKHR-presentMode-01281
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

oh

**Comment by Kaydax** [comment]
Your GPU does not support vulkan nor what is required by wasabi in order to run.
